prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema>
prefix cc: <http://creativecommons.org/ns#>
prefix ic: <http://imi.go.jp/ns/core/rdf#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ud: <http://localhost:3030/univ#>

SELECT ?subject ?predicate ?object
WHERE {
  ?subject ic:ID型 "1101102".
  ?subject ic:名称 ?object
}
LIMIT 100

# {
#   "head": {
#     "vars": [ "subject" , "predicate" , "object" ]
#   } ,
#   "results": {
#     "bindings": [
#       {
#         "subject": { "type": "bnode" , "value": "b0" } ,
#         "object": { "type": "literal" , "value": "フレッシュマン・セミナー" }
#       } ,
#       {
#         "subject": { "type": "bnode" , "value": "b1" } ,
#         "object": { "type": "literal" , "value": "フレッシュマン・セミナー" }
#       }
#     ]
#   }
# }
